services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - ./start.sh:/start.sh
    environment:
      - JEKYLL_ENV=development
    command: /bin/sh -c "/start.sh"
